databases:
  - name: movies_catalog_db
    databaseName: movies_catalog_production
    user: movies_catalog_db_user
    plan: free

services:
  - type: web
    name: movies-catalog
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec rails db:migrate && bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: movies_catalog_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SENDGRID_USERNAME
        sync: false
      - key: SENDGRID_PASSWORD
        sync: false
      - key: APP_DOMAIN
        sync: false
      - key: DEVISE_MAILER_SENDER
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled